global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'refined-jiji-backend'
    static_configs:
      - targets: ['refined-jiji-backend:5000']
    scrape_interval: 5s
    metrics_path: '/metrics'
    params:
      format: ['prometheus']

  - job_name: 'refined-jiji-webapp'
    static_configs:
      - targets: ['refined-jiji-webapp:3000']
    scrape_interval: 5s
    metrics_path: '/api/metrics'
    params:
      format: ['prometheus']

  - job_name: 'postgres'
    static_configs:
      - targets: ['refined-jiji-postgres:5432']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['refined-jiji-redis:6379']
    scrape_interval: 30s